### ISSUE TITLE
New class for statistics

### ISSUE THREAD

**Issue by ej-z** [SER516/ProjectTwo_Team08#1]
It would be better to move the statistics to class rather than keep it in ClientMain.

**Comment by Bala000** [comment]
Can refer to how stats class in server side is implemented if it's helpful. Would suggest implementing it as an inner class if only used inside a single class or else separate class.

**Comment by ghost** [comment]
Why do we need a stats class on the server? We don’t maintain any stats on the server as far a I’m aware.

**Comment by Bala000** [comment]
I believe that we need to maintain highest value, lowest value and frequency data that we get from the UI to inform serverthread, where these values are made use for generating data to be sent to client

**Comment by ghost** [comment]
Got it. I've added a Stats class in client. Closing the issue.
